import { useState } from 'react';
import { Bot, ChevronDown, Send, Sparkles, User, X } from 'lucide-react';
import { chatSuggestions, searchGames } from '@/lib/aiEngine';
import type { Game } from '@/types';

interface ChatAssistantProps { onNavigateGame: (game: Game) => void; onNavigateSearch: (query: string) => void; }
interface Message { role: 'assistant' | 'user'; text: string; games?: Game[]; }

export function ChatAssistant({ onNavigateGame, onNavigateSearch }: ChatAssistantProps) {
  const [open, setOpen] = useState(false);
  const [input, setInput] = useState('');
  const [messages, setMessages] = useState<Message[]>([{ role: 'assistant', text: 'Hey, I’m GameMind. Tell me what kind of experience you’re in the mood for and I’ll find something that fits.' }]);
  const send = (text = input) => { if (!text.trim()) return; const results = searchGames(text).slice(0, 3).map((item) => item.game); setMessages((current) => [...current, { role: 'user', text }, { role: 'assistant', text: `I found ${results.length} strong matches. Based on your request, I’d start with ${results[0]?.title || 'a fresh search'}.`, games: results }]); setInput(''); };
  return <div className="fixed bottom-5 right-5 z-40"><button onClick={() => setOpen(!open)} className={`w-14 h-14 rounded-2xl bg-gradient-to-br from-neon-purple to-neon-blue flex items-center justify-center shadow-[0_0_25px_rgba(168,85,247,0.5)] hover:scale-105 transition-transform ${open ? 'rotate-6' : ''}`} aria-label="Open GameMind assistant">{open ? <X className="w-6 h-6 text-white" /> : <Bot className="w-6 h-6 text-white" />}</button>{open && <div className="absolute bottom-16 right-0 w-[calc(100vw-40px)] sm:w-96 glass-strong rounded-2xl overflow-hidden shadow-2xl animate-scale-in"><div className="p-4 border-b border-white/10 flex items-center gap-3"><div className="w-9 h-9 rounded-xl bg-gradient-to-br from-neon-purple to-neon-cyan flex items-center justify-center"><Bot className="w-5 h-5 text-white" /></div><div><p className="font-display font-bold text-white">GameMind</p><p className="text-[11px] text-neon-cyan">AI game assistant · online</p></div><button onClick={() => setOpen(false)} className="ml-auto text-slate-500 hover:text-white"><ChevronDown className="w-4 h-4" /></button></div><div className="h-80 overflow-y-auto p-3 space-y-3">{messages.map((message, i) => <div key={i} className={`flex gap-2 ${message.role === 'user' ? 'flex-row-reverse' : ''}`}><div className={`w-6 h-6 rounded-full flex items-center justify-center shrink-0 ${message.role === 'user' ? 'bg-white/10' : 'bg-neon-purple/20'}`}>{message.role === 'user' ? <User className="w-3 h-3 text-slate-300" /> : <Sparkles className="w-3 h-3 text-neon-purple" />}</div><div className={`max-w-[80%] rounded-xl px-3 py-2 text-xs ${message.role === 'user' ? 'bg-neon-purple/20 text-white' : 'glass text-slate-300'}`}><p>{message.text}</p>{message.games && <div className="space-y-1.5 mt-2">{message.games.map((game) => <button key={game.id} onClick={() => onNavigateGame(game)} className="w-full text-left flex items-center gap-2 p-1.5 rounded-lg hover:bg-white/10"><img src={game.artwork} alt={game.title} className="w-9 h-7 object-cover rounded" /><span className="text-white truncate">{game.title}</span></button>)}</div>}</div></div>)}{messages.length === 1 && <div className="pt-2 space-y-1.5">{chatSuggestions.slice(0, 3).map((suggestion) => <button key={suggestion} onClick={() => send(suggestion)} className="w-full text-left chip">{suggestion}</button>)}</div>}</div><div className="p-3 border-t border-white/10 flex gap-2"><input value={input} onChange={(e) => setInput(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && send()} placeholder="Ask GameMind anything…" className="flex-1 glass rounded-lg px-3 py-2 text-xs text-white placeholder-slate-500 outline-none" /><button onClick={() => send()} className="w-9 h-9 rounded-lg bg-neon-purple flex items-center justify-center text-white hover:bg-neon-violet transition-colors"><Send className="w-4 h-4" /></button></div></div>}</div>;
}
