import type { Game } from '../types';

export const games: Game[] = [
  {
    id: 'cyberpunk-2077',
    title: 'Cyberpunk 2077',
    genres: ['RPG', 'FPS'],
    platforms: ['PC', 'PlayStation', 'Xbox'],
    multiplayer: 'Single-player',
    rating: 4.3,
    releaseYear: 2020,
    developer: 'CD Projekt Red',
    description: 'Strong match for your futuristic open-world and cyberpunk preferences.',
    longDescription: 'An open-world, action-adventure story set in Night City, a megalopolis obsessed with power, glamour, and body modification. Play as V, a mercenary outlaw going after a one-of-a-kind implant that is the key to immortality.',
    artwork: 'https://images.pexels.com/photos/17195067/pexels-photo-17195067.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    tags: ['RPG', 'Open World', 'Cyberpunk', 'Action'],
    difficulty: 'Hard',
    playtime: '40-60 hours',
    mood: ['Intense', 'Atmospheric', 'Epic'],
    graphicsStyle: '3D',
    price: '$59.99',
    ageRating: 'Mature',
    features: ['Open World', 'Character Customization', 'Branching Story', 'Neon Aesthetic'],
    whyYoullLike: ['Futuristic cyberpunk setting matches your request', 'Fast-paced combat with futuristic weapons', 'Deep RPG mechanics with open-world freedom', 'Neon-drenched visual style throughout'],
    gameplay: 'First-person RPG with shooting mechanics, hacking, dialogue choices, and a massive open world. Combat blends gunplay, melee, and cybernetic abilities.',
    aiSummary: 'A sprawling cyberpunk RPG that nails the neon-soaked futuristic aesthetic. The open world and combat systems align strongly with your preference for fast-paced, futuristic experiences.',
    reviews: [
      { author: 'NightCityRunner', rating: 5, text: 'The atmosphere is unmatched. Night City feels alive.' },
      { author: 'V_Merc', rating: 4, text: 'Incredible story and world. Some rough edges but unforgettable.' },
    ],
    similarIds: ['deus-ex', 'observer', 'ghostrunner'],
  },
  {
    id: 'valorant',
    title: 'Valorant',
    genres: ['FPS'],
    platforms: ['PC'],
    multiplayer: 'Multiplayer',
    rating: 4.6,
    releaseYear: 2020,
    developer: 'Riot Games',
    description: 'Tactical 5v5 character-based shooter with precise gunplay and agent abilities.',
    longDescription: 'A 5v5 character-based tactical shooter where precise gunplay meets unique agent abilities. Blend your style and experience on a global, competitive stage.',
    artwork: 'https://images.pexels.com/photos/28122495/pexels-photo-28122495.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    tags: ['FPS', 'Tactical', 'Competitive', 'Multiplayer'],
    difficulty: 'Hard',
    playtime: 'Unlimited',
    mood: ['Competitive', 'Intense', 'Thrilling'],
    graphicsStyle: '3D',
    price: 'Free',
    ageRating: 'Teen',
    features: ['Competitive Ranked', 'Agent Abilities', 'Esports', 'Anti-Cheat'],
    whyYoullLike: ['Multiplayer shooter matches your core request', 'Fast-paced tactical combat', 'Competitive scene with ranked play', 'Unique agent abilities add depth'],
    gameplay: '5v5 rounds where attackers plant a spike and defenders try to stop them. Each agent has unique abilities. Gunplay is precise and punishing.',
    aiSummary: 'A top-tier competitive multiplayer FPS. The tactical depth and precise gunplay make it perfect for players seeking fast-paced, skill-based multiplayer shooting.',
    reviews: [
      { author: 'Ace_Carrier', rating: 5, text: 'Best tactical shooter on the market. The gunplay is crisp.' },
      { author: 'SageMain', rating: 4, text: 'Great competitive experience, toxic community sometimes.' },
    ],
    similarIds: ['overwatch-2', 'apex-legends', 'cs2'],
  },
  {
    id: 'apex-legends',
    title: 'Apex Legends',
    genres: ['FPS'],
    platforms: ['PC', 'PlayStation', 'Xbox', 'Nintendo Switch'],
    multiplayer: 'Multiplayer',
    rating: 4.5,
    releaseYear: 2019,
    developer: 'Respawn Entertainment',
    description: 'Battle royale hero shooter with fast movement, squad-based tactics, and futuristic weapons.',
    longDescription: 'A free-to-play hero shooter battle royale game set in the Titanfall universe. Squads of three compete to be the last team standing with unique legends and abilities.',
    artwork: 'https://images.pexels.com/photos/8108327/pexels-photo-8108327.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    tags: ['FPS', 'Battle Royale', 'Multiplayer', 'Sci-Fi'],
    difficulty: 'Hard',
    playtime: 'Unlimited',
    mood: ['Competitive', 'Intense', 'Thrilling'],
    graphicsStyle: '3D',
    price: 'Free',
    ageRating: 'Teen',
    features: ['Battle Royale', 'Hero System', 'Squad Play', 'Fast Movement'],
    whyYoullLike: ['Futuristic sci-fi weapons and setting', 'Fast-paced multiplayer combat', 'Squad-based tactics with unique legends', 'Smooth movement and gunplay'],
    gameplay: '60-player battle royale in squads of 3. Each legend has passive, tactical, and ultimate abilities. Loot, fight, and survive the shrinking ring.',
    aiSummary: 'A fast-paced futuristic battle royale with hero abilities and squad tactics. The sci-fi aesthetic and multiplayer shooting make it a strong match.',
    reviews: [
      { author: 'WraithMain', rating: 5, text: 'Movement feels incredible. Best BR movement system.' },
      { author: 'LootGoblin', rating: 4, text: 'Fun with friends, solo queue can be rough.' },
    ],
    similarIds: ['valorant', 'overwatch-2', 'fortnite'],
  },
  {
    id: 'overwatch-2',
    title: 'Overwatch 2',
    genres: ['FPS'],
    platforms: ['PC', 'PlayStation', 'Xbox', 'Nintendo Switch'],
    multiplayer: 'Multiplayer',
    rating: 3.9,
    releaseYear: 2022,
    developer: 'Blizzard Entertainment',
    description: 'Team-based hero shooter with diverse roster and objective-focused multiplayer combat.',
    longDescription: 'A free-to-play team-based shooter with a constantly expanding roster of heroes. Fight across varied maps and modes in 5v5 team battles.',
    artwork: 'https://images.pexels.com/photos/14976666/pexels-photo-14976666.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    tags: ['FPS', 'Hero Shooter', 'Multiplayer', 'Team'],
    difficulty: 'Medium',
    playtime: 'Unlimited',
    mood: ['Competitive', 'Thrilling'],
    graphicsStyle: 'Cartoon',
    price: 'Free',
    ageRating: 'Teen',
    features: ['Hero Roster', '5v5 Battles', 'Ranked Play', 'Seasonal Events'],
    whyYoullLike: ['Multiplayer team shooter experience', 'Diverse hero roster with unique abilities', 'Objective-based gameplay variety', 'Active competitive community'],
    gameplay: '5v5 team battles across multiple modes. Heroes fill tank, damage, and support roles with unique abilities and ultimates.',
    aiSummary: 'A colorful team-based hero shooter. Great for players who want multiplayer FPS action with ability-driven teamplay.',
    reviews: [
      { author: 'SupportMain', rating: 4, text: 'Fun with friends, the 5v5 shift changed things.' },
      { author: 'DPSDiff', rating: 3, text: 'Matchmaking could be better but gameplay is solid.' },
    ],
    similarIds: ['valorant', 'apex-legends', 'paladins'],
  },
  {
    id: 'elden-ring',
    title: 'Elden Ring',
    genres: ['RPG', 'Adventure'],
    platforms: ['PC', 'PlayStation', 'Xbox'],
    multiplayer: 'Both',
    rating: 4.8,
    releaseYear: 2022,
    developer: 'FromSoftware',
    description: 'Epic dark fantasy open-world RPG with challenging combat and vast exploration.',
    longDescription: 'Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring and become an Elden Lord in the Lands Between. A vast world full of danger and discovery.',
    artwork: 'https://images.pexels.com/photos/1278540/pexels-photo-1278540.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    tags: ['RPG', 'Open World', 'Souls-like', 'Dark Fantasy'],
    difficulty: 'Very Hard',
    playtime: '60-100+ hours',
    mood: ['Epic', 'Atmospheric', 'Intense'],
    graphicsStyle: '3D',
    price: '$59.99',
    ageRating: 'Mature',
    features: ['Open World', 'Boss Fights', 'Character Builds', 'Co-op'],
    whyYoullLike: ['Epic dark fantasy world to explore', 'Deep RPG build customization', 'Satisfying challenging combat', 'Optional co-op multiplayer'],
    gameplay: 'Open-world action RPG with Souls-like combat. Explore the Lands Between, fight bosses, find gear, and build your character. Co-op and PvP available.',
    aiSummary: 'A masterpiece of open-world RPG design. The challenging combat and vast exploration make it essential for RPG fans seeking an epic adventure.',
    reviews: [
      { author: 'TarnishedOne', rating: 5, text: 'Game of the generation. The world design is incredible.' },
      { author: 'MaleniaSlayer', rating: 5, text: 'Hardest boss I have ever fought. Worth every death.' },
    ],
    similarIds: ['baldurs-gate-3', 'darksouls', 'witcher-3'],
  },
  {
    id: 'baldurs-gate-3',
    title: "Baldur's Gate 3",
    genres: ['RPG', 'Strategy'],
    platforms: ['PC', 'PlayStation', 'Xbox'],
    multiplayer: 'Both',
    rating: 4.9,
    releaseYear: 2023,
    developer: 'Larian Studios',
    description: 'Story-rich D&D RPG with turn-based combat, deep choices, and co-op multiplayer.',
    longDescription: 'Gather your party and return to the Forgotten Realms in a tale of fellowship and betrayal, sacrifice and survival, and the lure of absolute power. Based on Dungeons & Dragons 5th edition.',
    artwork: 'https://images.pexels.com/photos/9968434/pexels-photo-9968434.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    tags: ['RPG', 'Turn-Based', 'Story-Driven', 'D&D'],
    difficulty: 'Medium',
    playtime: '80-120+ hours',
    mood: ['Epic', 'Atmospheric'],
    graphicsStyle: '3D',
    price: '$59.99',
    ageRating: 'Mature',
    features: ['Turn-Based Combat', 'Branching Story', 'Co-op Campaign', 'Character Creation'],
    whyYoullLike: ['Incredible story-driven RPG experience', 'Deep tactical turn-based combat', 'Meaningful choices that shape the story', 'Up to 4-player co-op campaign'],
    gameplay: 'Turn-based RPG following D&D 5e rules. Build a party, make choices, fight tactically, and explore a massive story with branching paths.',
    aiSummary: 'A genre-defining RPG with unparalleled player choice. The story depth and co-op support make it perfect for RPG lovers.',
    reviews: [
      { author: 'DiceRoller', rating: 5, text: 'Best RPG in a decade. The choices actually matter.' },
      { author: 'AstarionFan', rating: 5, text: 'The character writing is phenomenal. 200 hours and counting.' },
    ],
    similarIds: ['elden-ring', 'witcher-3', 'disco-elysium'],
  },
  {
    id: 'witcher-3',
    title: 'The Witcher 3: Wild Hunt',
    genres: ['RPG', 'Adventure'],
    platforms: ['PC', 'PlayStation', 'Xbox', 'Nintendo Switch'],
    multiplayer: 'Single-player',
    rating: 4.9,
    releaseYear: 2015,
    developer: 'CD Projekt Red',
    description: 'Story-driven open-world RPG with mature narrative, monster hunting, and choice.',
    longDescription: 'As war rages on and monstrous creatures roam the Northern Kingdoms, you take on the greatest contract of your life — tracking down the Child of Prophecy, a living weapon on a path of destruction.',
    artwork: 'https://images.pexels.com/photos/14332269/pexels-photo-14332269.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    tags: ['RPG', 'Open World', 'Story-Driven', 'Fantasy'],
    difficulty: 'Medium',
    playtime: '50-100+ hours',
    mood: ['Epic', 'Atmospheric'],
    graphicsStyle: '3D',
    price: '$39.99',
    ageRating: 'Mature',
    features: ['Open World', 'Monster Hunting', 'Gwent', 'Multiple Endings'],
    whyYoullLike: ['One of the best story-driven RPGs ever made', 'Rich open world full of meaningful side quests', 'Deep combat with signs and oils', 'Mature, branching narrative'],
    gameplay: 'Open-world action RPG. Play as Geralt, hunt monsters, make choices, and explore a vast world with two massive expansions.',
    aiSummary: 'A landmark story-driven RPG. The world-building and narrative quality make it essential for RPG fans.',
    reviews: [
      { author: 'GeraltFan', rating: 5, text: 'The gold standard for RPGs. Nothing has topped it.' },
      { author: 'GwentMaster', rating: 5, text: 'Came for the story, stayed for Gwent.' },
    ],
    similarIds: ['elden-ring', 'baldurs-gate-3', 'cyberpunk-2077'],
  },
  {
    id: 'portal-2',
    title: 'Portal 2',
    genres: ['Puzzle'],
    platforms: ['PC', 'PlayStation', 'Xbox'],
    multiplayer: 'Both',
    rating: 4.9,
    releaseYear: 2011,
    developer: 'Valve',
    description: 'Relaxing yet brilliant first-person puzzle game with a co-op campaign and iconic humor.',
    longDescription: 'The sequel to the acclaimed first-person puzzle game. Features a single-player campaign and a separate co-op campaign with two robots. Use a portal gun to solve mind-bending spatial puzzles.',
    artwork: 'https://images.pexels.com/photos/33551076/pexels-photo-33551076.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    tags: ['Puzzle', 'Co-op', 'Story-Driven', 'Sci-Fi'],
    difficulty: 'Medium',
    playtime: '8-12 hours',
    mood: ['Relaxing', 'Cozy', 'Atmospheric'],
    graphicsStyle: '3D',
    price: '$9.99',
    ageRating: 'Everyone 10+',
    features: ['Portal Mechanics', 'Co-op Campaign', 'Level Editor', 'Story Mode'],
    whyYoullLike: ['Perfect relaxing puzzle experience', 'Brilliant co-op campaign for two players', 'Iconic humor and writing', 'Short and satisfying campaign'],
    gameplay: 'First-person puzzle solving with a portal gun that creates linked portals on surfaces. Co-op mode features two robots solving puzzles together.',
    aiSummary: 'A masterpiece of puzzle design. The co-op mode and relaxing difficulty curve make it perfect for a chill gaming session.',
    reviews: [
      { author: 'StillAlive', rating: 5, text: 'Perfect game. The co-op is pure joy.' },
      { author: 'CaveJohnson', rating: 5, text: 'When life gives you lemons, make Portal 2.' },
    ],
    similarIds: ['the-witness', 'baba-is-you', 'tetris-effect'],
  },
  {
    id: 'the-witness',
    title: 'The Witness',
    genres: ['Puzzle', 'Adventure'],
    platforms: ['PC', 'PlayStation', 'Xbox', 'Mobile'],
    multiplayer: 'Single-player',
    rating: 4.4,
    releaseYear: 2016,
    developer: 'Thekla, Inc.',
    description: 'Open-world puzzle game on a beautiful island. Relaxing, meditative, and deeply clever.',
    longDescription: 'Explore an island filled with natural and architectural wonders. Solve line puzzles on panels to unlock new areas and uncover the islands mysteries.',
    artwork: 'https://images.pexels.com/photos/13695383/pexels-photo-13695383.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    tags: ['Puzzle', 'Open World', 'Mystery', 'Relaxing'],
    difficulty: 'Hard',
    playtime: '15-25 hours',
    mood: ['Relaxing', 'Atmospheric', 'Cozy'],
    graphicsStyle: '3D',
    price: '$19.99',
    ageRating: 'Teen',
    features: ['Open World', 'Line Puzzles', 'Environmental Puzzles', 'No Handholding'],
    whyYoullLike: ['Relaxing island atmosphere for calm play', 'Deep puzzle design that rewards observation', 'No time pressure or combat', 'Beautiful open world to explore'],
    gameplay: 'First-person exploration. Solve panel-based line puzzles to progress. The island teaches you rules through observation with no text or tutorials.',
    aiSummary: 'A meditative open-world puzzle game. Perfect for relaxing, thoughtful play sessions with no pressure.',
    reviews: [
      { author: 'PuzzlePro', rating: 5, text: 'The puzzle design is genius. Pure epiphany moments.' },
      { author: 'IslandWanderer', rating: 4, text: 'Beautiful and calming. Some puzzles are tough though.' },
    ],
    similarIds: ['portal-2', 'baba-is-you', 'monument-valley'],
  },
  {
    id: 'civilization-6',
    title: 'Civilization VI',
    genres: ['Strategy', 'Simulation'],
    platforms: ['PC', 'PlayStation', 'Xbox', 'Nintendo Switch', 'Mobile'],
    multiplayer: 'Both',
    rating: 4.5,
    releaseYear: 2016,
    developer: 'Firaxis Games',
    description: 'Turn-based strategy where you build an empire, research tech, and conquer the world.',
    longDescription: 'Explore, expand, exploit, and exterminate. Lead a civilization from the Stone Age to the Information Age. Wage war, conduct diplomacy, and advance your culture.',
    artwork: 'https://images.pexels.com/photos/7086525/pexels-photo-7086525.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    tags: ['Strategy', 'Turn-Based', 'Empire', '4X'],
    difficulty: 'Medium',
    playtime: 'Unlimited',
    mood: ['Epic', 'Chill'],
    graphicsStyle: '3D',
    price: '$59.99',
    ageRating: 'Everyone 10+',
    features: ['Turn-Based Strategy', 'Empire Building', 'Multiplayer', 'Tech Tree'],
    whyYoullLike: ['Deep strategic gameplay', 'Multiplayer for competitive empire-building', 'Endless replayability', 'Multiple victory paths'],
    gameplay: 'Turn-based 4X strategy. Found cities, build wonders, research technology, and compete for victory through science, culture, domination, or religion.',
    aiSummary: 'The quintessential turn-based strategy game. Deep, replayable, and perfect for both relaxed and competitive play.',
    reviews: [
      { author: 'OneMoreTurn', rating: 5, text: 'It is 3am. I said one more turn 6 hours ago.' },
      { author: 'GandhiNukes', rating: 4, text: 'Great strategy. Gandhi is terrifying as always.' },
    ],
    similarIds: ['age-of-empires-4', 'stellaris', 'xcom-2'],
  },
  {
    id: 'stellaris',
    title: 'Stellaris',
    genres: ['Strategy', 'Simulation'],
    platforms: ['PC', 'PlayStation', 'Xbox'],
    multiplayer: 'Both',
    rating: 4.4,
    releaseYear: 2016,
    developer: 'Paradox Interactive',
    description: 'Grand strategy in space. Explore the galaxy, build an interstellar empire, and survive.',
    longDescription: 'Explore a vast galaxy full of wonder. Forge a galactic empire, send science ships into the unknown, and discover anomalies and mysteries.',
    artwork: 'https://images.pexels.com/photos/796206/pexels-photo-796206.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    tags: ['Strategy', 'Sci-Fi', 'Space', 'Grand Strategy'],
    difficulty: 'Hard',
    playtime: 'Unlimited',
    mood: ['Epic', 'Atmospheric', 'Chill'],
    graphicsStyle: '3D',
    price: '$39.99',
    ageRating: 'Everyone 10+',
    features: ['Galaxy Exploration', 'Empire Customization', 'Multiplayer', 'Story Events'],
    whyYoullLike: ['Futuristic sci-fi space setting', 'Deep strategic empire management', 'Multiplayer galactic conquest', 'Endless emergent stories'],
    gameplay: 'Grand strategy in space. Explore, colonize, diplomacy, and warfare across a procedurally generated galaxy with customizable empires.',
    aiSummary: 'A deep space grand strategy game. The sci-fi setting and emergent storytelling make it perfect for strategic space exploration.',
    reviews: [
      { author: 'GalaxyRuler', rating: 5, text: 'The stories that emerge are incredible. Every playthrough is unique.' },
      { author: 'Diplomat', rating: 4, text: 'Steep learning curve but incredibly rewarding.' },
    ],
    similarIds: ['civilization-6', 'xcom-2', 'endless-space-2'],
  },
  {
    id: 'forza-horizon-5',
    title: 'Forza Horizon 5',
    genres: ['Racing'],
    platforms: ['PC', 'PlayStation', 'Xbox'],
    multiplayer: 'Both',
    rating: 4.8,
    releaseYear: 2021,
    developer: 'Playground Games',
    description: 'Open-world racing in a vibrant Mexico. Fun, accessible, and visually stunning.',
    longDescription: 'Lead breathtaking expeditions across the vibrant landscapes of Mexico. Race through deserts, jungles, cities, and beaches in the worlds greatest automotive festival.',
    artwork: 'https://images.pexels.com/photos/20196376/pexels-photo-20196376.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    tags: ['Racing', 'Open World', 'Multiplayer', 'Arcade'],
    difficulty: 'Easy',
    playtime: 'Unlimited',
    mood: ['Thrilling', 'Chill', 'Competitive'],
    graphicsStyle: 'Realistic',
    price: '$59.99',
    ageRating: 'Everyone',
    features: ['Open World', 'Car Collection', 'Online Racing', 'Seasons'],
    whyYoullLike: ['Accessible and fun racing experience', 'Beautiful open world to explore', 'Online multiplayer racing', 'Huge car roster to collect'],
    gameplay: 'Open-world arcade racing. Drive hundreds of cars across a massive map, complete events, and race online. Seasons change the world dynamically.',
    aiSummary: 'The best open-world racing game. Accessible, beautiful, and endlessly fun for both casual and competitive racing fans.',
    reviews: [
      { author: 'SpeedDemon', rating: 5, text: 'Best racing game ever made. The world is gorgeous.' },
      { author: 'CarCollector', rating: 5, text: '500 cars and counting. Pure driving joy.' },
    ],
    similarIds: ['gran-turismo-7', 'need-for-speed', 'mario-kart'],
  },
  {
    id: 'resident-evil-4',
    title: 'Resident Evil 4',
    genres: ['Horror', 'Adventure'],
    platforms: ['PC', 'PlayStation', 'Xbox'],
    multiplayer: 'Single-player',
    rating: 4.8,
    releaseYear: 2023,
    developer: 'Capcom',
    description: 'Survival horror remake with tense combat, atmosphere, and a thrilling campaign.',
    longDescription: 'Survive as Leon Kennedy in a rural European village plagued by horror. A modern remake of the legendary survival horror game with updated controls and stunning visuals.',
    artwork: 'https://images.pexels.com/photos/14648586/pexels-photo-14648586.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    tags: ['Horror', 'Survival', 'Action', 'Story-Driven'],
    difficulty: 'Hard',
    playtime: '15-20 hours',
    mood: ['Atmospheric', 'Thrilling', 'Intense'],
    graphicsStyle: '3D',
    price: '$59.99',
    ageRating: 'Mature',
    features: ['Survival Horror', 'Resource Management', 'Boss Fights', 'New Game Plus'],
    whyYoullLike: ['Atmospheric horror experience', 'Tense survival combat', 'Thrilling story-driven campaign', 'Masterful pacing and tension'],
    gameplay: 'Third-person survival horror. Manage resources, fight infected villagers, solve puzzles, and survive a terrifying campaign.',
    aiSummary: 'A masterful survival horror remake. The tension, atmosphere, and combat make it essential for horror fans.',
    reviews: [
      { author: 'HorrorFan', rating: 5, text: 'The remake is perfect. Even better than the original.' },
      { author: 'LeonKennedy', rating: 5, text: 'Tense, scary, and action-packed. Capcom nailed it.' },
    ],
    similarIds: ['silent-hill-2', 'dead-space', 'amnesia'],
  },
  {
    id: 'dont-starve',
    title: "Don't Starve Together",
    genres: ['Survival', 'Indie'],
    platforms: ['PC', 'PlayStation', 'Xbox', 'Nintendo Switch'],
    multiplayer: 'Co-op',
    rating: 4.6,
    releaseYear: 2016,
    developer: 'Klei Entertainment',
    description: 'Co-op survival with a unique art style. Gather, craft, and survive the wilderness.',
    longDescription: 'A standalone multiplayer expansion to the uncompromising wilderness survival game. Enter a strange and unexplored world with friends.',
    artwork: 'https://images.pexels.com/photos/3433326/pexels-photo-3433326.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    tags: ['Survival', 'Co-op', 'Indie', 'Crafting'],
    difficulty: 'Hard',
    playtime: 'Unlimited',
    mood: ['Atmospheric', 'Cozy', 'Intense'],
    graphicsStyle: '2D',
    price: '$14.99',
    ageRating: 'Teen',
    features: ['Co-op Survival', 'Crafting', 'Procedural Worlds', 'Seasons'],
    whyYoullLike: ['Co-op survival with friends', 'Unique hand-drawn art style', 'Deep crafting and base building', 'Challenging but rewarding'],
    gameplay: 'Co-op survival. Gather resources, craft tools, build a base, and survive against creatures, seasons, and sanity loss.',
    aiSummary: 'A charming but punishing co-op survival game. The unique art style and deep crafting make it a standout indie.',
    reviews: [
      { author: 'SurvivalExpert', rating: 5, text: 'Best co-op survival game. So much depth.' },
      { author: 'BaseBuilder', rating: 4, text: 'Incredible with friends. Brutal solo.' },
    ],
    similarIds: ['terraria', 'minecraft', 'valheim'],
  },
  {
    id: 'minecraft',
    title: 'Minecraft',
    genres: ['Survival', 'Simulation', 'Adventure'],
    platforms: ['PC', 'PlayStation', 'Xbox', 'Nintendo Switch', 'Mobile'],
    multiplayer: 'Both',
    rating: 4.7,
    releaseYear: 2011,
    developer: 'Mojang Studios',
    description: 'Block-based sandbox survival and creativity. Build, mine, and explore infinite worlds.',
    longDescription: 'Explore infinite worlds and build everything from simple homes to grand castles. Play in creative mode with unlimited resources or survive in survival mode.',
    artwork: 'https://images.pexels.com/photos/26765046/pexels-photo-26765046.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    tags: ['Survival', 'Sandbox', 'Building', 'Multiplayer'],
    difficulty: 'Easy',
    playtime: 'Unlimited',
    mood: ['Cozy', 'Chill', 'Relaxing'],
    graphicsStyle: 'Pixel Art',
    price: '$29.99',
    ageRating: 'Everyone 10+',
    features: ['Sandbox Building', 'Survival Mode', 'Multiplayer', 'Modding'],
    whyYoullLike: ['Relaxing creative sandbox', 'Survival mode for challenge', 'Multiplayer with friends', 'Endless possibilities'],
    gameplay: 'Block-based sandbox. Mine resources, craft, build, and survive in a procedurally generated world. Creative and survival modes.',
    aiSummary: 'The ultimate sandbox game. Perfect for relaxing creative play or challenging survival with friends.',
    reviews: [
      { author: 'BlockBuilder', rating: 5, text: '10 years and still playing. Infinite replayability.' },
      { author: 'RedstoneEngineer', rating: 5, text: 'You can build anything. The creativity is unmatched.' },
    ],
    similarIds: ['dont-starve', 'terraria', 'valheim'],
  },
  {
    id: 'hades',
    title: 'Hades',
    genres: ['Indie', 'RPG'],
    platforms: ['PC', 'PlayStation', 'Xbox', 'Nintendo Switch', 'Mobile'],
    multiplayer: 'Single-player',
    rating: 4.9,
    releaseYear: 2020,
    developer: 'Supergiant Games',
    description: 'Fast-paced roguelike with incredible art, story, and satisfying combat. Under 30 hours.',
    longDescription: 'Escape the Underworld as the immortal prince of the dead. A god-defying roguelike with thousands of viable story builds and a gripping narrative.',
    artwork: 'https://images.pexels.com/photos/289367/pexels-photo-289367.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    tags: ['Roguelike', 'Indie', 'Action', 'Story-Driven'],
    difficulty: 'Hard',
    playtime: '20-40 hours',
    mood: ['Intense', 'Atmospheric', 'Thrilling'],
    graphicsStyle: '2D',
    price: '$24.99',
    ageRating: 'Teen',
    features: ['Roguelike Runs', 'Boon System', 'Story Progression', 'Voice Acting'],
    whyYoullLike: ['Fast-paced satisfying combat', 'Incredible art and storytelling', 'Perfect length for a focused experience', 'Deep build variety'],
    gameplay: 'Action roguelike. Fight through the Underworld, receive god boons, die, and come back stronger with permanent story progression.',
    aiSummary: 'A masterpiece of the roguelike genre. The fast combat, art, and story integration make it an essential indie.',
    reviews: [
      { author: 'ZagreusFan', rating: 5, text: 'Perfect roguelike. The story integration is genius.' },
      { author: 'BoonStacker', rating: 5, text: 'Every run feels fresh. 200 hours in and still loving it.' },
    ],
    similarIds: ['dead-cells', 'hollow-knight', 'slay-the-spire'],
  },
  {
    id: 'stardew-valley',
    title: 'Stardew Valley',
    genres: ['Simulation', 'Indie', 'RPG'],
    platforms: ['PC', 'PlayStation', 'Xbox', 'Nintendo Switch', 'Mobile'],
    multiplayer: 'Both',
    rating: 4.9,
    releaseYear: 2016,
    developer: 'ConcernedApe',
    description: 'Cozy farming and life sim. Relax, farm, mine, and build relationships. Perfectly relaxing.',
    longDescription: 'You have inherited your grandfathers old farm plot. Armed with hand-me-down tools and a few coins, you set out to begin your new life.',
    artwork: 'https://images.pexels.com/photos/3011826/pexels-photo-3011826.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    tags: ['Farming Sim', 'Cozy', 'Life Sim', 'Relaxing'],
    difficulty: 'Easy',
    playtime: '50-100+ hours',
    mood: ['Relaxing', 'Cozy', 'Chill'],
    graphicsStyle: 'Pixel Art',
    price: '$14.99',
    ageRating: 'Everyone 10+',
    features: ['Farming', 'Multiplayer Co-op', 'Mining', 'Relationships'],
    whyYoullLike: ['The ultimate relaxing cozy game', 'Farming, fishing, and relationships', 'Multiplayer co-op farming', 'Endless content for the price'],
    gameplay: 'Farming and life sim. Plant crops, raise animals, mine, fish, build relationships, and restore the valley. Co-op multiplayer supported.',
    aiSummary: 'The gold standard for cozy games. Perfect for relaxing, low-pressure play sessions alone or with friends.',
    reviews: [
      { author: 'FarmLife', rating: 5, text: 'Most relaxing game ever made. 400 hours and counting.' },
      { author: 'CozyGamer', rating: 5, text: 'Pure serotonin. Perfect for unwinding.' },
    ],
    similarIds: ['animal-crossing', 'minecraft', 'spiritfarer'],
  },
  {
    id: 'subnautica',
    title: 'Subnautica',
    genres: ['Survival', 'Adventure'],
    platforms: ['PC', 'PlayStation', 'Xbox', 'Nintendo Switch'],
    multiplayer: 'Single-player',
    rating: 4.6,
    releaseYear: 2018,
    developer: 'Unknown Worlds',
    description: 'Underwater survival on an alien ocean planet. Beautiful, terrifying, and atmospheric.',
    longDescription: 'Dive into an underwater adventure on an alien ocean planet. Scavenge resources, build bases, and uncover the mystery of the planet.',
    artwork: 'https://images.pexels.com/photos/13838693/pexels-photo-13838693.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    tags: ['Survival', 'Underwater', 'Open World', 'Atmospheric'],
    difficulty: 'Medium',
    playtime: '30-50 hours',
    mood: ['Atmospheric', 'Thrilling', 'Relaxing'],
    graphicsStyle: '3D',
    price: '$29.99',
    ageRating: 'Teen',
    features: ['Underwater Exploration', 'Base Building', 'Story Mystery', 'Creature Encounters'],
    whyYoullLike: ['Beautiful atmospheric underwater world', 'Survival crafting and base building', 'Thrilling creature encounters', 'Mystery-driven story'],
    gameplay: 'Underwater survival. Dive deep, gather resources, build bases and submarines, and uncover why you crashed on an alien ocean world.',
    aiSummary: 'A uniquely atmospheric survival game. The underwater exploration and mystery make it unforgettable.',
    reviews: [
      { author: 'DeepDiver', rating: 5, text: 'The thalassophobia is real. Incredible experience.' },
      { author: 'BaseArchitect', rating: 4, text: 'Beautiful and terrifying. Building bases is so satisfying.' },
    ],
    similarIds: ['dont-starve', 'minecraft', 'valheim'],
  },
  {
    id: 'ghostrunner',
    title: 'Ghostrunner',
    genres: ['FPS', 'Indie'],
    platforms: ['PC', 'PlayStation', 'Xbox', 'Nintendo Switch'],
    multiplayer: 'Single-player',
    rating: 4.4,
    releaseYear: 2020,
    developer: 'One More Level',
    description: 'Fast-paced cyberpunk first-person parkour slasher. One-hit-one-kill, neon, and speed.',
    longDescription: 'A hardcore first-person slasher set in a dystopian cyberpunk structure. One-hit-one-kill mechanics make for intense, fast-paced combat.',
    artwork: 'https://images.pexels.com/photos/32660203/pexels-photo-32660203.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    tags: ['FPS', 'Cyberpunk', 'Parkour', 'Fast-Paced'],
    difficulty: 'Very Hard',
    playtime: '8-12 hours',
    mood: ['Intense', 'Thrilling', 'Atmospheric'],
    graphicsStyle: 'Neon',
    price: '$29.99',
    ageRating: 'Mature',
    features: ['One-Hit Kill', 'Parkour Movement', 'Time Slow', 'Cyberpunk Setting'],
    whyYoullLike: ['Fast-paced cyberpunk combat', 'Neon futuristic visual style', 'Intense one-hit-one-kill gameplay', 'Satisfying parkour movement'],
    gameplay: 'First-person parkour slasher. Wall-run, slide, dash, and slice enemies. Die in one hit, respawn instantly. Fast and precise.',
    aiSummary: 'A pure adrenaline cyberpunk experience. The fast pace and neon aesthetic make it perfect for short, intense sessions.',
    reviews: [
      { author: 'SpeedRunner', rating: 5, text: 'Pure flow state. The movement is incredible.' },
      { author: 'NeonNinja', rating: 4, text: 'Brutal but so satisfying when you nail a level.' },
    ],
    similarIds: ['cyberpunk-2077', 'superhot', 'neon-white'],
  },
  {
    id: 'tetris-effect',
    title: 'Tetris Effect: Connected',
    genres: ['Puzzle'],
    platforms: ['PC', 'PlayStation', 'Xbox', 'Nintendo Switch', 'VR'],
    multiplayer: 'Both',
    rating: 4.7,
    releaseYear: 2018,
    developer: 'Enhance',
    description: 'Mesmerizing Tetris with music, visuals, and flow. Relaxing and meditative puzzle bliss.',
    longDescription: 'Tetris like you have never seen or heard it before. Mesmerizing, gorgeous, and completely addictive with music that reacts to your play.',
    artwork: 'https://images.pexels.com/photos/30933673/pexels-photo-30933673.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    tags: ['Puzzle', 'Music', 'Relaxing', 'VR'],
    difficulty: 'Easy',
    playtime: '10-30 hours',
    mood: ['Relaxing', 'Cozy', 'Atmospheric'],
    graphicsStyle: 'Neon',
    price: '$29.99',
    ageRating: 'Everyone',
    features: ['Music Synced', 'VR Support', 'Co-op Mode', 'Journey Mode'],
    whyYoullLike: ['Perfect relaxing puzzle experience', 'Music and visuals create a flow state', 'Co-op and competitive modes', 'VR support for immersion'],
    gameplay: 'Tetris with reactive music and visuals. Journey mode takes you through themed stages. Co-op and competitive multiplayer modes included.',
    aiSummary: 'A transcendent take on Tetris. The music and visuals make it the most relaxing puzzle experience available.',
    reviews: [
      { author: 'FlowState', rating: 5, text: 'It is Tetris but it makes me cry. The music is incredible.' },
      { author: 'ZenGamer', rating: 5, text: 'Most relaxing game I own. Perfect for unwinding.' },
    ],
    similarIds: ['portal-2', 'the-witness', 'monument-valley'],
  },
];

export function getGameById(id: string): Game | undefined {
  return games.find((g) => g.id === id);
}

export function getSimilarGames(game: Game): Game[] {
  return game.similarIds.map(getGameById).filter((g): g is Game => g !== undefined);
}
