import { Bookmark, Clock3, Gamepad2, Heart, Plus, Sparkles, Trash2 } from 'lucide-react';
import type { CreatedGame, Game } from '@/types';

interface LibraryPageProps { library: Game[]; createdGames: CreatedGame[]; onNavigateGame: (game: Game) => void; onRemove: (game: Game) => void; onCreate: () => void; }

export function LibraryPage({ library, createdGames, onNavigateGame, onRemove, onCreate }: LibraryPageProps) {
  const recentlyPlayed = library.slice(0, 4); const recommendations = library.slice(2, 6);
  return <div className="max-w-7xl mx-auto px-4 md:px-6 py-8 pb-20"><div className="flex items-end justify-between mb-8"><div><div className="flex items-center gap-2 text-neon-purple text-xs uppercase tracking-widest mb-2"><Bookmark className="w-4 h-4" /> Personal space</div><h1 className="font-display text-4xl font-bold text-white">My Library</h1><p className="text-slate-400 mt-2">Your games, your taste, your next adventure.</p></div><button onClick={onCreate} className="btn-primary hidden sm:inline-flex"><Plus className="w-4 h-4" /> Create Game</button></div><LibrarySection icon={Heart} title="Favorites" games={library.slice(0, 4)} onNavigate={onNavigateGame} onRemove={onRemove} empty="Add games from Discovery to build your favorites." /><LibrarySection icon={Clock3} title="Recently Played" games={recentlyPlayed} onNavigate={onNavigateGame} onRemove={onRemove} empty="Your recently played games will show up here." /><LibrarySection icon={Sparkles} title="AI Recommendations" games={recommendations} onNavigate={onNavigateGame} onRemove={onRemove} empty="Ask GameMind to find your next game." /><section className="mt-10"><div className="flex items-center justify-between mb-4"><div className="flex items-center gap-2"><Gamepad2 className="w-5 h-5 text-neon-cyan" /><h2 className="section-title text-xl">Created Games</h2></div><button onClick={onCreate} className="text-sm text-neon-cyan hover:text-white transition-colors">Create another</button></div>{createdGames.length === 0 ? <div className="glass-card p-8 text-center"><Gamepad2 className="w-8 h-8 mx-auto mb-3 text-slate-600" /><p className="text-sm text-slate-400 mb-4">Your AI-generated prototypes will live here.</p><button onClick={onCreate} className="btn-ghost text-sm">Open AI Game Studio</button></div> : <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{createdGames.map((created) => <div key={created.id} className="glass-card overflow-hidden"><div className="h-32 bg-gradient-to-br from-neon-purple/30 via-ink-800 to-neon-cyan/20 flex items-center justify-center"><Gamepad2 className="w-10 h-10 text-neon-cyan" /></div><div className="p-4"><h3 className="font-display font-bold text-white">{created.title}</h3><p className="text-sm text-slate-400 mt-1 mb-3">{created.description}</p><span className="tag bg-neon-purple/10 text-neon-purple border border-neon-purple/20">{created.genre}</span></div></div>)}</div>}</section></div>;
}
function LibrarySection({ icon: Icon, title, games, onNavigate, onRemove, empty }: { icon: typeof Heart; title: string; games: Game[]; onNavigate: (game: Game) => void; onRemove: (game: Game) => void; empty: string }) { return <section className="mb-10"><div className="flex items-center gap-2 mb-4"><Icon className="w-5 h-5 text-neon-purple" /><h2 className="section-title text-xl">{title}</h2></div>{games.length === 0 ? <div className="glass-card p-6 text-sm text-slate-500">{empty}</div> : <div className="grid grid-cols-2 md:grid-cols-4 gap-4">{games.map((game) => <div key={game.id} className="glass-card glass-card-hover overflow-hidden group relative"><button onClick={() => onNavigate(game)} className="w-full text-left"><div className="aspect-video overflow-hidden"><img src={game.artwork} alt={game.title} className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500" /></div><div className="p-3"><h3 className="text-sm font-semibold text-white truncate">{game.title}</h3><p className="text-xs text-slate-400">{game.genres[0]} · {game.releaseYear}</p></div></button><button onClick={() => onRemove(game)} className="absolute top-2 right-2 w-7 h-7 rounded-lg glass-strong flex items-center justify-center text-slate-300 hover:text-rose-400 opacity-0 group-hover:opacity-100 transition-opacity" aria-label={`Remove ${game.title}`}><Trash2 className="w-3.5 h-3.5" /></button></div>)}</div>}</section>; }
